### ISSUE TITLE
Hello Please i want make bookmark database colections

### ISSUE THREAD

**Issue by prengus** [FranP-code/Open-Telegram-to-Notion-Bot#5]
Could you please tell me how i use motion database for my bookmark i usually use browser google chrome to bookmark, i use this apps post some url with my telegram and its link not clickable when arrived at notion.so. my question, how to make it urls clickable? Also font  my url In notion.so looks bigger, how to set it smaller so easy to read on my phone? Thank you

My format usually:
1. url
2. Folders
3. tag

**Comment by FranP-code** [comment]
Hello!

In this case, you should create a database and include one row with the url type. The bot it's prepared for validate and communicate the url texts to notion, but only with the url row type.

Then, when you want to save a bookmark, send first **the name of the bookmark**, and then define the url and tags of the bookmark.

Demo:

[Screencast from 2022-12-20 22-10-58.webm](https://user-images.githubusercontent.com/76450203/208797176-1f33d6ac-1849-46ef-b30c-68d4035433d2.webm)
